FALSE EQU 0
TRUE  EQU 1

PAUSE_WORLD_DURING_INTRO  EQU TRUE ; script pause
PAUSE_WORLD_DURING_SAVE   EQU TRUE ; engine pause
PAUSE_WORLD_DURING_BATTLE EQU TRUE ; script pause

DEFAULT_CLOCK_MULTIPLIER EQU 0
INDOOR_MULTIPLIER        EQU 6
GATE_MULTIPLIER          EQU 6
CAVE_MULTIPLIER          EQU 15
DUNGEON_MULTIPLIER       EQU 15
TOWN_MULTIPLIER          EQU 30
ROUTE_MULTIPLIER         EQU 60